### ISSUE TITLE
Audio support

### ISSUE THREAD

**Issue by mustafamasvi** [instaglitch/instaglitch#1]
Hi @mat-sz,
Can we have audio support to manage multiple audios?  
Or can you tell me a way I will try to add it?

**Comment by mustafamasvi** [comment]
Hi @mat-sz ,
I want to extend the functionality and add audio, text, emoji, and other types. 
What would be the best practice? 

Thanks

**Comment by mat-sz** [comment]
@mustafamasvi Unfortunately this is out of scope for this project.
