### ISSUE TITLE
Chromakey Filter

### ISSUE THREAD

**Issue by mustafamasvi** [instaglitch/instaglitch#2]
Hi @mat-sz ,

I am trying to add the chromaKey filter, which requires two Channel, (iTexture is already defined in fxGlue library and works with the current layer). 
How do I add the other channel which is on another layer?
 
ShadartoyEffect: https://www.shadertoy.com/view/XsfGzn

Steps:
1. Made changed toabove shaderToy by replacing the channel0 with iTexture, fragColor -> gl_FragColor and other changes as mentioned in fxGlue 
2. No GlueProgramError when adding the shadar.
3. The only issue is with how to pass the two-channel, I have replaced both channel(0 and 1) with iTexture. 

Thanks for your help.

**Comment by mat-sz** [comment]
@mustafamasvi This might be useful if the replaced color would just become transparent instead of selecting another texture. I'll look into this.

**Comment by mat-sz** [comment]
Added in 1892cedb69b451715612ce61e945c59744a33869.
