### ISSUE TITLE
Add Filter to specific Source.

### ISSUE THREAD

**Issue by mustafamasvi** [instaglitch/instaglitch#5]
Hi @mat-sz, 
Currently, when a filter is applied, it applies to all the sources.

If I am having two videos in a single frame, something like a pip mode, (or just Logo on the top right)
I would like to add some effect to the main video but not necessarily add the same effect to the smaller video or logo. 

if the feature asked is not in the current scope of the project, can you please guide how can I achieve it on a high level or with some code snippet? 

![image](https://user-images.githubusercontent.com/18447601/211509903-058b0480-8c7d-49b3-a089-c8676da039db.png)
Scanlines Filter to be applied to the dancer(green video, layer 3) and not in the image (layer 2).

Thank you for all your support.

**Comment by mat-sz** [comment]
Added layer grouping feature in latest release, marking as solved.
